kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sharedfs
provisioner: kvaps/sharedfs
parameters:
  mountpoint: /stor/sharedfs
  directory: images
  fsType: ext4
  mmpUpdateInterval: "5"
  iqn: "iqn.2018-09.org.loopback.sharedfs"
  lun: "1"
mountOptions:
  - noatime
  - nodiratime
reclaimPolicy: Retain
