apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iscsi-sheepdog-publisher
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iscsi-sheepdog-publisher
  template:
    metadata:
      labels:
        app: iscsi-sheepdog-publisher
    spec:
      hostNetwork: true
      containers:
      - name: publisher
        imagePullPolicy: Always
        image: "kvaps/iscsi-sheepdog-publisher"
        env:
        - name: IQN
          value: "iqn.2018-09.org.loopback.sheepdog"
        volumeMounts:
        - name: run
          mountPath: "/run"

      volumes:
      - name: run
        hostPath:
          path: "/run"
