apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iscsi-sharedfs-provisioner
spec:
  selector:
    matchLabels:
      app: iscsi-sharedfs-provisioner
  template:
    metadata:
      labels:
        app: iscsi-sharedfs-provisioner
    spec:
      hostNetwork: true
      serviceAccount: iscsi-sharedfs-provisioner
      containers:
      - name: provisioner
        command: [ "/iscsi-sharedfs-provisioner" ]
        imagePullPolicy: Always
        image: "kvaps/iscsi-sharedfs-provisioner"
        env:
        - name: PROVISIONER_NAME
          value: "kvaps/sharedfs"
        volumeMounts:
        - name: stor
          mountPath: /stor
          mountPropagation: HostToContainer

      - name: deleter
        command: [ "/iscsi-sharedfs-deleter" ]
        imagePullPolicy: Always
        image: "kvaps/iscsi-sharedfs-provisioner"
        env:
        - name: PROVISIONER_NAME
          value: "kvaps/sharedfs"
        volumeMounts:
        - name: stor
          mountPath: /stor
          mountPropagation: HostToContainer

      volumes:
      - name: stor
        hostPath:
          path: "/stor"
